export interface Vehicle {
  id: number;
  vehicle_name: string;
  vehicle_number: string;
  model?: string | null;
  make?: string | null;
  capacity?: number | null;
  status?: string;
  gps_device_id?: string | null;
  battery?: number | null;
  lat?: number | null;
  lng?: number | null;
  speed?: number | null;
  lastGpsUpdate?: string | null;

  // Legacy fields kept optional so older shared screens still compile.
  vehicle_type?: string;
  rc_number?: string;
  rc_isued_date?: string;
  rc_expiry_date?: string;
  manufacturer?: string;
  vehicle_model?: string;
  manufacturing_year?: string;
  fuel_type?: string;
  seating_capacity?: number;
  vehicle_color?: string;
  kilometers_driven?: number;
  driver?: string;
  route?: string;
  gps_device?: string;
  gps_installation_date?: string;
  permit_type?: string;
  permit_number?: string;
  permit_issue_date?: string;
  permit_expiry_date?: string;
  ownership_type?: string;
  vendor_name?: string;
  vendor_aadhar_number?: string;
  vendor_pan_number?: string;
  vendor_contact_number?: string;
  vendor_organization_name?: string;
  insurance_provider_name?: string;
  insurance_policy_number?: string;
  insurance_issued_date?: string;
  insurance_expiry_date?: string;
  fitness_certificate_number?: string;
  fitness_issued_date?: string;
  fitness_expiry_date?: string;
  pollution_certificate_number?: string;
  pollution_issued_date?: string;
  pollution_expiry_date?: string;
  tax_renewable_date?: string;
  last_service_date?: string;
  next_service_due_date?: string;
  tyre_replacement_due_date?: string;
  battery_replacement_due_date?: string;
  fire_extinguisher?: string;
  first_aid_kit?: string;
  cctv_installed?: string;
  panic_button_installed?: string;
  remarks?: string;
  insurance_doc?: string;
  rc_book_doc?: string;
  puc_doc?: string;
  fitness_certificate?: string;
  permit_copy?: string;
  gps_installation_proof?: string;
  saftey_certificate?: string;
  vendor_pan?: string;
  vendor_adhaar?: string;
  vendor_bank_proof?: string;
  vendor_contract_proof?: string;
  vedor_company_registration_doc?: string;
  // NEW FIELDS
  gps_sim_number?: string;
  beacon_count?: number;
  assigned_driver_id?: string;
  assigned_route_id?: string;
  owner_name?: string;
  owner_contact_number?: string;
  organisation_fleet_name?: string;
  owner_id_proof?: string;
  vendor_agreement?: string;
  created_at?: string;
  updated_at?: string;
  driver_first_name?: string;
  driver_last_name?: string;
  driver_mobile_number?: string;
  driver_employee_id?: string;
}
